/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.libreria_arancione;

import com.libreria_arancione.boundary.LibreriaArancione;
import com.libreria_arancione.entity.Library;
import com.libreria_arancione.entity.Student;
import jakarta.persistence.RollbackException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author utentepc
 */
public class WindowGuiSellingBook extends javax.swing.JDialog {

        String bookSelected;
        String studentSelected;

        /**
         * Creates new form WindowGui
         */
        public WindowGuiSellingBook() {
                initComponents();
                addEventListeners();
        }

        public void addEventListeners() {
                jPurchase.addActionListener(this::onPurchase);
                btnDeleteBook.addActionListener(this::btnDeleteBookActionPerformed);
                btnDeleteStudent.addActionListener(this::btnDeleteStudentActionPerformed);
                btnAddStudent.addActionListener(this::btnAddStudentActionPerformed);
                btnAddBook.addActionListener(this::btnAddBookActionPerformed);
                jBtnSearchBook.addActionListener(this::jBtnSearchBookActionPerformed);
                jBtnSearchStudent.addActionListener(this::jBtnSearchStudentActionPerformed);
                btnUpdateBook.addActionListener(this::btnUpdateBookActionPerformed);
                btnUpdateStudent.addActionListener(this::btnUpdateStudentActionPerformed);
                jBooksSold.addActionListener(this::jBooksSoldActionPerformed);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txStudent = new javax.swing.JTextField();
                txPrice = new javax.swing.JTextField();
                txBook = new javax.swing.JTextField();
                jPurchase = new javax.swing.JButton();
                btnDeleteBook = new javax.swing.JButton();
                btnDeleteStudent = new javax.swing.JButton();
                btnAddStudent = new javax.swing.JButton();
                btnAddBook = new javax.swing.JButton();
                jBtnSearchBook = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                jListStudents = new javax.swing.JList<>();
                jBtnSearchStudent = new javax.swing.JButton();
                btnUpdateBook = new javax.swing.JButton();
                btnUpdateStudent = new javax.swing.JButton();
                jScrollPane5 = new javax.swing.JScrollPane();
                jListBooks = new javax.swing.JList<>();
                jBooksSold = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setText("Search Book");

                jLabel2.setText("Search Student");

                jLabel3.setText("Price");

                jPurchase.setText("Finish Purchase");

                btnDeleteBook.setText("Delete Book");
                btnDeleteStudent.setText("Delete Student");
                btnAddStudent.setText("Add Student");

                jBtnSearchBook.setText("Search");

                btnAddBook.setText("Add Book");

                jScrollPane4.setViewportView(jListStudents);

                jBtnSearchStudent.setText("Search");

                btnUpdateBook.setText("Update Book");

                btnUpdateStudent.setText("Update Student");

                jScrollPane5.setViewportView(jListBooks);

                jBooksSold.setText("Books Sold");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(22, 22, 22)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(73, 73, 73)
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                70,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(462, 462,
                                                                                                                                                462)
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(69, 69, 69)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(btnAddBook,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                130,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(btnDeleteBook,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                130,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(btnUpdateBook,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                130,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(387, 387,
                                                                                                                                                387)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(btnDeleteStudent,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                130,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(btnUpdateStudent,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                130,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(btnAddStudent,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                130,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addContainerGap(
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(txBook,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                249,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGap(79, 79, 79)
                                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(txPrice,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                139,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(jBtnSearchBook)))
                                                                                                                                .addGap(34, 34, 34)
                                                                                                                                .addComponent(txStudent,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                275,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jBtnSearchStudent))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(347, 347,
                                                                                                                                                347)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGap(9, 9, 9)
                                                                                                                                                                .addComponent(jPurchase,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                180,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGap(37, 37, 37)
                                                                                                                                                                .addComponent(jScrollPane4,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                249,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addComponent(jBooksSold,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                180,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                .addContainerGap(1131,
                                                                                                                Short.MAX_VALUE))))
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addGap(46, 46, 46)
                                                                                .addComponent(jScrollPane5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                282,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(1749,
                                                                                                Short.MAX_VALUE))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(33, 33, 33)
                                                                                                                                .addComponent(jLabel2))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                .addContainerGap()
                                                                                                                                                .addComponent(jLabel1)))
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(txBook,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                48,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jBtnSearchBook)))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(12, 12, 12)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(txStudent,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                48,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jBtnSearchStudent))))
                                                                                                .addGap(27, 27, 27)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jScrollPane4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(txPrice,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                44,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(36, 36, 36)
                                                                                                                                .addComponent(jPurchase,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                38,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                68,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnAddBook,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                32,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnUpdateBook,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                32,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnDeleteBook,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                32,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(22, 22, 22))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(btnAddStudent,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                32,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(btnUpdateStudent,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                32,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(27, 27, 27)
                                                                                                                .addComponent(btnDeleteStudent,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                32,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(47, 47, 47)))
                                                                .addComponent(jBooksSold,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 101, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addGap(146, 146, 146)
                                                                                .addComponent(jScrollPane5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(351,
                                                                                                Short.MAX_VALUE))));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void onPurchase(java.awt.event.ActionEvent evt) {

                try {
                        int price = Integer.parseInt(txPrice.getText());
                        bookSelected = jListBooks.getSelectedValue();
                        studentSelected = jListStudents.getSelectedValue();

                        // After setting up the selection listeners, look for the student
                        if (studentSelected != null && bookSelected != null) {

                                String[] parts = studentSelected.split(" - ");
                                int id = Integer.parseInt(parts[0]);
                                Student studentById = LibreriaArancione.findStudentById(id);

                                String[] partsBook = bookSelected.split(" - ");
                                int idBook = Integer.parseInt(partsBook[0]);
                                Library bookById = LibreriaArancione.findBookById(idBook);

                                LibreriaArancione.Purchase(bookById, studentById, price);

                        }

                        dispose();
                        new WindowGuiSellingBook().setVisible(true);

                }

                catch (RollbackException e) {
                        JOptionPane.showMessageDialog(null, "Something is wrong");
                        System.out.println(e);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERROR: All Fields Required");
                        System.out.println(e);
                }

                JOptionPane.showMessageDialog(null, "BOOK SOLD");

        }

        private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {
                this.dispose();
                new WindowGuiAddStudent().setVisible(true);
        }

        private void jBtnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBtnSearchBookActionPerformed

                DefaultListModel<String> listModel = new DefaultListModel();
                String book = txBook.getText();

                List<Library> bookByTitle = LibreriaArancione.findBookByTitle(book);

                for (Library bk : bookByTitle) {
                        listModel.addElement(bk.getId() + " - " + bk.getTitle() + " by: " + bk.getAuthor());
                        System.out.println("title: " + bk.getTitle() + " author: " + bk.getAuthor());
                }

                jListBooks.setModel(listModel);
        }

        private void jBtnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {

                DefaultListModel<String> listStudentModel = new DefaultListModel();
                String student = txStudent.getText();
                System.out.println(student);

                List<Student> findStudentByName = LibreriaArancione.findStudentsByName(student);

                System.out.println(findStudentByName);
                for (Student std : findStudentByName) {
                        listStudentModel.addElement(std.getId() + " - " + std.getName() + " " + std.getSurname());
                        System.out.println("name;" + std.getName() + " " + std.getSurname());
                }

                jListStudents.setModel(listStudentModel);

        }// GEN-LAST:event_jBtnSearchStudentActionPerformed

        private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteBookActionPerformed
                bookSelected = jListBooks.getSelectedValue();
                String[] parts = bookSelected.split(" - ");
                int id = Integer.parseInt(parts[0]);
                LibreriaArancione.deleteBook(id);
                jBtnSearchBookActionPerformed(evt);

        }// GEN-LAST:event_btnDeleteBookActionPerformed

        private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {
                bookSelected = jListBooks.getSelectedValue();
                String[] parts = bookSelected.split(" - ");
                int id = Integer.parseInt(parts[0]);
                Library book = LibreriaArancione.findBookById(id);
                dispose();

                System.out.println(book);
                new WindowGuiAddBook(id).setVisible(true);
        }

        private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {
                this.dispose();
                new WindowGuiAddBook().setVisible(true);

        }

        private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {
                studentSelected = jListStudents.getSelectedValue();
                String[] parts = studentSelected.split(" - ");
                int id = Integer.parseInt(parts[0]);
                LibreriaArancione.deleteStudent(id);
                jBtnSearchStudentActionPerformed(evt);
        }

        private void jBooksSoldActionPerformed(java.awt.event.ActionEvent evt) {
                this.dispose();
                new WindowGuiBooksSold().setVisible(true);
        }

        private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateStudentActionPerformed
                studentSelected = jListStudents.getSelectedValue();
                String[] parts = studentSelected.split(" - ");
                int id = Integer.parseInt(parts[0]);
                Student student = LibreriaArancione.findStudentById(id);
                dispose();

                System.out.println(student);
                new WindowGuiAddStudent(id).setVisible(true);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiSellingBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiSellingBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiSellingBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiSellingBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                WindowGuiSellingBook dialog = new WindowGuiSellingBook();
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAddBook;
        private javax.swing.JButton btnAddStudent;
        private javax.swing.JButton btnDeleteBook;
        private javax.swing.JButton btnDeleteStudent;
        private javax.swing.JButton btnUpdateBook;
        private javax.swing.JButton btnUpdateStudent;
        private javax.swing.JButton jBooksSold;
        private javax.swing.JButton jBtnSearchBook;
        private javax.swing.JButton jBtnSearchStudent;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JList<String> jListBooks;
        private javax.swing.JList<String> jListStudents;
        private javax.swing.JButton jPurchase;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTextField txBook;
        private javax.swing.JTextField txPrice;
        private javax.swing.JTextField txStudent;
        // End of variables declaration//GEN-END:variables
}
