package com.libreria_arancione;

import com.libreria_arancione.boundary.LibreriaArancione;
import com.libreria_arancione.control.Store;
import com.libreria_arancione.entity.Student;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;

/**
 *
 * @author utentepc
 */
public class WindowGuiAddStudent extends javax.swing.JDialog {
        /**
         * Creates new form WindowGui
         */
        private boolean update;
        private Student updateStudent;

        public WindowGuiAddStudent() {
                this.update = false;
                initComponents();
                addEventListeners();
        }

        public WindowGuiAddStudent(int id) {
                this.update = true;
                updateStudent = Store.findStudentById(id);
                System.out.println(updateStudent);
                initComponents();
                txName.setText(updateStudent.getName());
                txSurname.setText(updateStudent.getSurname());
                txEmail.setText(updateStudent.getEmail());
                txPhone.setText(updateStudent.getPhone());
                txSchoolYear.setText(updateStudent.getPhone());
                addEventListeners();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                txSurname = new javax.swing.JTextField();
                txPhone = new javax.swing.JTextField();
                txEmail = new javax.swing.JTextField();
                txSchoolYear = new javax.swing.JTextField();
                txName = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                jShowCustomer = new javax.swing.JTextPane();
                btnAddStudent = new javax.swing.JButton();
                btnReturn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setText("Name");

                jLabel2.setText("Surname");

                jLabel3.setText("Phone");

                jLabel4.setText("Email");

                jLabel5.setText("School Year");

                jShowCustomer.setEditable(false);
                jScrollPane1.setViewportView(jShowCustomer);

                btnAddStudent.setText("click");
                btnReturn.setText("return");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                557,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(178, 178, 178))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(297, 297, 297)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel3)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel2)
                                                                                                .addComponent(jLabel1))
                                                                                .addComponent(jLabel5))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                33,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(txSurname,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                480,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(txName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                480,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(txPhone,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                480,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(58, 58, 58)
                                                                                                .addComponent(btnAddStudent)
                                                                                                .addComponent(btnReturn)
                                                                                                .addContainerGap(76,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(31, 31, 31)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(txEmail,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                480,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txSchoolYear))))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(49, 49, 49)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel1))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txSurname,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                48,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel2)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(53, 53, 53)
                                                                                                .addComponent(btnAddStudent)
                                                                                                .addComponent(btnReturn)))
                                                                .addGap(9, 9, 9)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txPhone,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3))
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txEmail,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txSchoolYear,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5))
                                                                .addGap(66, 66, 66)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                121,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(30, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void addEventListeners() {

                btnAddStudent.addActionListener(this::addStudent);
                btnReturn.addActionListener(this::returnPage);

        }

        private void returnPage(ActionEvent evt) {
                dispose();
                new WindowGuiSellingBook().setVisible(true);
        }

        private void addStudent(ActionEvent evt) {

                String name = txName.getText();
                String surname = txSurname.getText();
                String phone = txPhone.getText();
                String email = txEmail.getText();
                String schoolYear = txSchoolYear.getText();
                try {
                        if (update) {
                                updateStudent.setName(name);
                                updateStudent.setSurname(surname);
                                updateStudent.setPhone(phone);
                                updateStudent.setEmail(email);
                                updateStudent.setSchoolYear(schoolYear);
                                LibreriaArancione.addStudent(name, surname, email, phone, schoolYear);
                        } else {
                                LibreriaArancione.addStudent(name, surname, email, phone, schoolYear);
                        }
                        this.dispose();
                        new WindowGuiSellingBook().setVisible(true);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERROR: All Fields Required");
                        System.out.println(e);
                }

        }
        // GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiAddStudent.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiAddStudent.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiAddStudent.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(WindowGuiAddStudent.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                WindowGuiAddStudent dialog = new WindowGuiAddStudent();
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAddStudent;
        private javax.swing.JButton btnReturn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextPane jShowCustomer;
        private javax.swing.JTextField txEmail;
        private javax.swing.JTextField txName;
        private javax.swing.JTextField txPhone;
        private javax.swing.JTextField txSchoolYear;
        private javax.swing.JTextField txSurname;
        // End of variables declaration//GEN-END:variables
}
